version: "3.2"
services:

  chat-api:
    container_name: chat-api
    image: private-gpt-app
    build:
      context: .
    entrypoint: gunicorn src.app:app -k uvicorn.workers.UvicornWorker --timeout 1500
    volumes:
      - ./:/src
    ports:
      - 8000:8000

  chat-ui:
    container_name: chat-ui
    image: private-gpt-app
    build:
      context: .
    entrypoint: streamlit run src/streamlit_app.py
    volumes:
      - ./:/src
    ports:
      - 8501:8501
