version: "3.2"
services:

  chat-api:
    container_name: chat-api
    image: private-gpt-app
    build:
      context: .
    entrypoint: uvicorn src.app:app --host 0.0.0.0 --port 8000
    volumes:
      - ./:/app
    ports:
      - 8000:8000

  chat-ui:
    container_name: chat-ui
    image: private-gpt-app
    build:
      context: .
    entrypoint: streamlit run src/streamlit_app.py
    volumes:
      - ./:/app
    ports:
      - 8501:8501
